### ISSUE TITLE
Cập nhật món > (Thêm) Lỗi định dạng giá của món

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#11]
Step (mô tả đến bước bị lỗi):
1. Đăng nhập vào role cửa hàng thành công
2. Chọn món nút "Thêm món"
3. Nhập đầy đủ thông tin (phần giá nhập: 20000.563)
4. Nhấn nút "Thêm món"

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):
1. Trường dữ liệu giá chuyển dấu chấm thành dấu phẩy, dù đã tự động thêm dấu chấm vào hàng chục 20.000,563. 
![image](https://github.com/user-attachments/assets/9cb28cc0-55ab-45d7-a9b3-13513f9676dc)
2. Nếu nhập 20.000 trường giá sẽ chỉ còn 20
![image](https://github.com/user-attachments/assets/61d072e7-7d83-44a3-bc04-b2be3d6e619a)

Expected Result:
Hệ thống thông báo: "Sai định dạng giá" khi nhập ký tự đặc biệt.

**Comment by phuczu13** [comment]
done
