### ISSUE TITLE
Cập nhật món > (Thêm) Phần "Tên món" gần như không có giới hạn ký tự

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#12]
Step (mô tả đến bước bị lỗi):
1. Đăng nhập vào role cửa hàng thành công
2. Chọn món nút "Thêm món"
3. Nhập đầy đủ thông tin (phần tên món copy 'đoạn văn' bất kỳ paste vào)
4. Nhấn nút "Thêm món"

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):
Trường dữ liệu tên món có giới hạn dữ liệu rất rất dài, gần như không có giới hạn ký tự dẫn đến bể giao diện sau khi thêm.
![image](https://github.com/user-attachments/assets/d0ed62a0-0554-4781-9634-772ba41ccbe7)

Expected Result:
Hệ thống thông báo: Phần "Tên món" vượt quá giới hạn ký tự.

**Comment by phuczu13** [comment]
done
