### ISSUE TITLE
Cập nhật món > (Sửa) Phần "Tên món" gần như không có giới hạn ký tự

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#13]
Step (mô tả đến bước bị lỗi):
1. Đăng nhập vào role cửa hàng thành công
2. Chọn món nút "Sửa" của món đã có bất kỳ
3. Sửa phần tên món (copy 'đoạn văn' bất kỳ paste vào)
4. Nhấn nút "Sửa"

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):
Trường dữ liệu tên món có giới hạn dữ liệu rất rất dài, gần như không có giới hạn ký tự dẫn đến sau khi sửa bị bể giao diện.
![image](https://github.com/user-attachments/assets/3f3687f4-20a4-4146-984f-05d5faff1d81)

Expected Result:
Hệ thống thông báo: Phần "Tên món" vượt quá giới hạn ký tự.

**Comment by phuczu13** [comment]
done
