### ISSUE TITLE
Cập nhật món > (Giao diện) Phần chiều cao thẻ chứa giá món, nút "Sửa", "Xóa" không bằng nhau 

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#14]
Step (mô tả đến bước bị lỗi):
1. Đăng nhập vào role của hàng thành công
2. Chọn nút "Thêm món"
3. Nhập đầy đủ thông tin của món (nhập mô tả dài nhiều dòng)
4. Nhấn nút "Thêm món"
5. Chọn nút "Sửa" của món đã có bất kỳ (trừ món vừa thêm)
6. Sửa tên món (nhập để tên món có từ 2 dòng trở lên)
7. Nhấn nút "Cập nhật"

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):
Dòng cuối cùng của các món chứa: Giá, nút sửa, nút xóa hiển thị không bằng nhau
![image](https://github.com/user-attachments/assets/fa6c87fc-2f69-4f49-aca2-e3b18025c4a2)

Expected Result:
Hệ thống hiện thị dòng cuối của tất cả món đều bằng nhau.

**Comment by phuczu13** [comment]
done
