### ISSUE TITLE
Cập nhật món > (Thêm) Giá có thể nhập số 0

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#15]
Step (mô tả đến bước bị lỗi):
1. Đăng nhập vào role cửa hàng thành công
2. Chọn nút "Thêm món"
3. Nhập đầy đủ thông tin của món (nhập giá món là số 0)
4. Nhấn nút "Thêm món"

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):
Sau khi nhập giá món là số 0 vẫn có thể thêm món như bình thường
![image](https://github.com/user-attachments/assets/f5afe32e-05a6-4bad-ae1b-05b29baf912f)

Expected Result:
Hệ thống thông báo giá không thể là số 0.

**Comment by phuczu13** [comment]
done
