### ISSUE TITLE
Cập nhật món > (Sửa) Giá có thể sửa thành số 0

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#16]
Step (mô tả đến bước bị lỗi):
1. Đăng nhập vào role cửa hàng thành công
2. Chọn món nút "Sửa" của món có sẵn
3. Sửa giá món là số 0
4. Nhấn nút "Cập nhật"

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):
Sau khi nhập giá món là số 0 vẫn có thể cập nhật món như bình thường
![image](https://github.com/user-attachments/assets/9f2a98d0-7610-4bc6-95f7-32b7bd470729)

Expected Result:
Hệ thống thông báo giá không thể là số 0.

**Comment by phuczu13** [comment]
done
