### ISSUE TITLE
Cập nhật món > (Giao diện) Phần thẻ chứa "giá món", nút "Sửa", "Xóa" bể khi giá quá dài

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#17]
Step (mô tả đến bước bị lỗi):
1. Đăng nhập vào role của hàng thành công
2. Chọn nút "Thêm món"
3. Nhập đầy đủ thông tin của món (nhập giá >= 10 số 0)
4. Nhấn nút "Thêm món"

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):
Dòng cuối cùng của các món chứa: Giá, nút sửa, nút xóa. 2 nút sửa, xóa bị out khỏi vùng quy định
![image](https://github.com/user-attachments/assets/456e6c63-dad3-48ad-b40f-60bcda45001a)

Expected Result:
Hệ thống hiện thị dòng cuối của tất cả món đều bằng nhau.

**Comment by phuczu13** [comment]
done
