### ISSUE TITLE
Cập nhật món phụ > (Giao diện) Mục "Món phụ" trên hearder bị sai

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#18]
Step (mô tả đến bước bị lỗi):
1. Đăng nhập vào role của hàng thành công
2. Nhìn lên thanh hearder

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):
Mục "Món phụ" vẫn là để là "Toppiing"
![image](https://github.com/user-attachments/assets/c72ccdcc-dc03-47c3-8bcb-ae611cf8c4c9)

Expected Result:
Hệ thống hiển thị danh mục "Món phụ.

**Comment by phuczu13** [comment]
done
