### ISSUE TITLE
Cập nhật món phụ > (Giao diện) Giá vẫn chưa có dấu ngăn cách giữa  đơn vị

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#19]
Step (mô tả đến bước bị lỗi):
1. Đăng nhập vào role của hàng thành công
2. Chọn mục "Món thêm"
3. Thêm món mới thành công
4. Quan sát giá của món mới thêm

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):
Giá của món sẽ có ngăn cách giữa 3 đơn vị, ví dụ: 2000 -> 2.000; 20000 -> 20.000; ....
![image](https://github.com/user-attachments/assets/d077a4e6-4d0d-4997-a02c-f2a59cd6d077)

Expected Result:
Hệ thống thông báo "Vui lòng điền đầy đủ thông tin" và giữ nguyên form chỉnh sửa món.

**Comment by phuczu13** [comment]
![image](https://github.com/user-attachments/assets/a4e60a30-c316-4ce7-b737-0938faa86872)
