### ISSUE TITLE
Cập nhật món phụ > (Thêm, Sửa) Giá có thể nhập ký tự đặc biệt

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#20]
Step (mô tả đến bước bị lỗi):
1. Đăng nhập vào role của hàng thành công
2. Chọn mục "Món thêm"
3. Thêm món phụ mới hoặc cập nhật món phụ đã có với trường dữ liệu giá là ký tự đặc biệt

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):
Ký tự đặc biệt vẫn có thể là giá món sau khi thêm hoặc sửa món phụ
![image](https://github.com/user-attachments/assets/9db9d548-be67-47ac-b244-0399a1ad2511)

Expected Result:
Hệ thống thông báo trường dữ liệu giá không hợp lệ.

**Comment by phuczu13** [comment]
done
