### ISSUE TITLE
Cập nhật món > (Xóa) Nhấn nút "Hủy" ở form xác nhận xóa

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#21]
Step (mô tả đến bước bị lỗi):
1. Đăng nhập vào role của hàng thành công
2. Chọn nút "Xóa" của món đã có bất kỳ
3. Nhấn nút "Hủy" trên form xác nhận xóa món

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):

Expected Result:
Hệ thống giữ lại món và quay lại trang món.

**Comment by phuczu13** [comment]
done
