### ISSUE TITLE
Cập nhật món phụ > (Thêm) Bấm nút "Hủy" khi thêm món phụ

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#23]
Step (mô tả đến bước bị lỗi):
1. Đăng nhập vào role của hàng thành công
2. Chọn mục "Món phụ" ở thanh Hearder
3. Chọn nút "Thêm món phụ"
4. Nhập đầy đủ thông tin của món phụ
5. Nhấn nút "Hủy"

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):

Expected Result:
Hệ thống không lưu thông tin món phụ và quay lại trang món phụ.

**Comment by phuczu13** [comment]
done
