### ISSUE TITLE
Cập nhật món phụ > (Thêm) Bỏ trống thông tin món phụ

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#24]
Step (mô tả đến bước bị lỗi):
1. Đăng nhập vào role của hàng thành công
2. Chọn mục "Món phụ" ở thanh Hearder
3. Chọn nút "Thêm món phụ"
4. Để trống 1 hoặc nhiều trường thông tin của món phụ
5. Nhấn nút "Thêm món phụ"

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):

Expected Result:
Hệ thống thông báo "Vui lòng điền đầy đủ thông tin".

**Comment by phuczu13** [comment]
done
