### ISSUE TITLE
Cập nhật món phụ > (Sửa) Chỉnh sửa "giá" món phụ thành công

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#25]
Step (mô tả đến bước bị lỗi):
1. Đăng nhập vào role của hàng thành công
2. Chọn mục "Món phụ" ở thanh Hearder
3. Chọn nút "Sửa" của món phụ đã có bất kỳ
4. Chỉnh sửa giá của món phụ
5. Nhấn nút "Cập nhật"

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):

Expected Result:
Hệ thống thông báo "Cập nhật món thành công" và quay lại trang món phụ.

**Comment by phuczu13** [comment]
ok
