### ISSUE TITLE
Cập nhật món phụ > (Xóa) Nhấn nút "Hủy" ở form xác nhận xóa

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#29]
Step (mô tả đến bước bị lỗi):
1. Đăng nhập vào role của hàng thành công
2. Chọn mục "Món phụ" ở thanh Hearder
3. Chọn nút "Xóa" của món phụ đã có bất kỳ
4. Nhấn nút "Hủy" ở form xác nhận xóa

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):

Expected Result:
Hệ thống giữ lại món và quay lại trang món.

**Comment by phuczu13** [comment]
done
