### ISSUE TITLE
Cập nhật trạng thái đơn hàng cửa hàng -> Cập nhật không thành công 

### ISSUE THREAD

**Issue by BaoNgoc2211** [BaoNgoc2211/DAPM#30]
**Steps:**
"1. Đăng nhập vào web role cửa hàng
2. Chọn mục đơn hàng trên thanh nav
3. Chọn Chờ xác nhận trên thanh menu
4. nhấn nút "Nhận đơn"

**Enviroment:** Trên laptop HP
**Trình duyệt:** Google chrome
**Result**
khách hàng đặt món thành công, không chuyển qua trạng thái đơn "Chờ xác nhận", mà chuyển thẳng qua trạng thái "Đã nhận" ở role cửa hàng
![bug1](https://github.com/user-attachments/assets/a005d552-f337-464d-868c-d7df1e989c80)

**Comment by BaoNgoc2211** [comment]
**Steps:**
"1. Đăng nhập vào web role cửa hàng
2. Chọn mục đơn hàng trên thanh nav
3. Chọn đã  trên thanh menu
4. nhấn nút "Hoàn thành"

**Enviroment**: Trên laptop HP
**Trình duyệt:** Google chrome

**Result**
Hiển thị thông báo xác nhận, nhấn xác nhận và chuyển qua trạng thái "Tìm tài xế"
![bug 2 1](https://github.com/user-attachments/assets/84f92f0f-4d86-41ef-896a-bcd813654fd0)

**Expected Result**
Chuyển đơn hàng qua trang trạng thái "Tìm tài xế"

**Comment by LucHandsome** [comment]
đã fix
