### ISSUE TITLE
Cập nhật thông tin cửa hàng -> Cập nhật thông tin cửa hàng không thành công

### ISSUE THREAD

**Issue by BaoNgoc2211** [BaoNgoc2211/DAPM#31]

**Comment by BaoNgoc2211** [comment]
**Steps:**
1. Khách hàng truy cập vào trang "Thông tin cửa hàng"
2. Hiển thị thông tin cửa hàng đã đăng ký

**Enviroment:** Trên laptop HP
**Trình duyệt:** Google chrome

**Result**
Thông tin cửa hàng trống, dù khi đăng nhập lần đầu đã đăng ký và nhập thông tin cửa hàng
![bug 2](https://github.com/user-attachments/assets/e97c9571-90c7-42d4-8b61-5ffea7636cac)

**Expected Result**
Hiển thị thông tin cửa hàng đã đăng ký

**Comment by LucHandsome** [comment]
đã fix
