### ISSUE TITLE
Cập nhật trạng thái đơn hàng cửa hàng ->Lỗi chuyển trang button "Hoàn thành"

### ISSUE THREAD

**Issue by BaoNgoc2211** [BaoNgoc2211/DAPM#33]
Steps:
"1. Đăng nhập vào web role cửa hàng
2. Chọn mục đơn hàng trên thanh nav
3. Chọn đã trên thanh menu
4. nhấn nút "Hoàn thành"

Enviroment: Trên laptop HP
Trình duyệt: Google chrome

Result
Hiển thị thông báo xác nhận, nhấn xác nhận và chuyển qua trạng thái "Tìm tài xế"
![bug 2 1](https://github.com/user-attachments/assets/6d7e089e-f27d-43c3-bdf2-389118d1f04c)

Expected Result
Chuyển đơn hàng qua trang trạng thái "Tìm tài xế"

**Comment by phuczu13** [comment]
ok
