### ISSUE TITLE
Tìm kiếm món ăn, quán ăn -> Kiểm tra kết quá trả về tìm kiếm 

### ISSUE THREAD

**Issue by BaoNgoc2211** [BaoNgoc2211/DAPM#34]
Step
1. Đăng nhập vào web role khách hành
2. Nhập nội dung tìm kiếm 
3. Nhấn enter

Enviroment: Trên laptop HP
Trình duyệt: Google chrome

Result
Không hiển thị kết quả tìm 
![Bug 4](https://github.com/user-attachments/assets/04b7f83e-2fdb-47cf-8e73-676d93bc859a)

Expected Result
Hiển thị danh sách món/ quán ăn

**Comment by phuczu13** [comment]
ok
