### ISSUE TITLE
Cập nhật giỏ hàng -> Tăng số lượng sản phẩm

### ISSUE THREAD

**Issue by BaoNgoc2211** [BaoNgoc2211/DAPM#38]
Steps:
Đăng nhập vào web role khách hàng
Tại trang home nhấn vào một sản phẩm bất kỳ và nhấn icon "+"
Nhấn vào giỏ hàng trên thanh navbar hiển thị thông tin giỏ hàng
Nhấn icon "+" để Tăng sản phẩm 

Enviroment: Trên laptop HP
Trình duyệt: Google chrome

Result
Chưa ràng buộc dữ liệu số sản phẩm tối đa
![Bug 8](https://github.com/user-attachments/assets/d25151c3-0a48-4dba-89ff-f5fd46ab07cf)

Expected Result
Tối đa mua được 20 sản phẩm một món

**Comment by phuczu13** [comment]
![image](https://github.com/user-attachments/assets/6291686b-0ec2-4900-b287-801acf9ffc6a)
tui thấy shopee nó cho chọn đến khi max số lượng tồn kho của shop luôn ấy bà
