### ISSUE TITLE
Xuất hóa 

### ISSUE THREAD

**Issue by BaoNgoc2211** [BaoNgoc2211/DAPM#39]
Steps:
1. Xem chi iết đơn hàng
2. Nhấn nút xuất hóa đơn
3. Hiển thị thông báo xác nhận 
3.1 Nhấn nút đồng ý 
3.1.1 Hiển thị thông báo thành công

Enviroment: Trên laptop HP
Trình duyệt: Google chrome

Result
Chưa có chức năng xuất hóa đơn
![Bug 9](https://github.com/user-attachments/assets/81db56fa-6cfa-4b4f-a20f-abee50cd7675)

Expected Result
Xuất hóa đơn qua máy in

**Comment by phuczu13** [comment]
done
