### ISSUE TITLE
Đăng kí tài khoản cửa hàng > Chức năng con mắt làm mờ mật khẩu

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#4]
Step (mô tả đến bước bị lỗi):
1. Khách hàng truy cập vào trang "Bắt đầu ... trở thành đối tác của chúng tôi".
2. Trang đăng nhập cửa hàng hiển thị.
3. Chọn nút "Đăng ký", dưới nút đăng nhập.
4. Nhập thông tin đăng ký.
5. Có thể chọn con mắt trong khung mật khẩu, nhập lại mật khẩu để hiện nội dùng trong ô.

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):
![image](https://github.com/user-attachments/assets/b5aaf770-f8a2-46ef-8780-0434241f8dcf)
- Con mắt chỉ hoạt động khi con trỏ văn bản đang trong ô mật khẩu, nhập lại mật khẩu lần đầu tiên. 
- Sau khi con trỏ văn bản chuyển qua ô khác hoặc biến mất vì chọn ở ngoài, con mắt sẽ biến mất vĩnh viễn.
- Cách duy nhất để kích hoạt lại con mắt là xóa hết nội dung trong ô sau đó nhập lại.

Expected Result:
Hệ thống tạo tài khoản thành công.

**Comment by phuczu13** [comment]
done
