### ISSUE TITLE
Xem chi tiết cửa hàng -> Kiểm tra cửa hàng mới tạo

### ISSUE THREAD

**Issue by BaoNgoc2211** [BaoNgoc2211/DAPM#40]
Steps:

1. Đăng nhập vào web role khách hàng
2. Tại trang home nhấn Quán ăn trên thanh nav
3. nhấn vào button "Xem tất cả các quán"

Enviroment: Trên laptop HP
Trình duyệt: Google chrome

Result
Hiển thị trang trắng
![bug 10 2](https://github.com/user-attachments/assets/be181db5-628a-45d8-85ed-987073a11816)
![bug 10 1](https://github.com/user-attachments/assets/940c6037-9059-4887-b023-f09ead4f7535)

Expected Result
Hiển thị tên của hàng mới tạo

**Comment by phuczu13** [comment]
done
