### ISSUE TITLE
Đặt món -> Kiểm tra trường thông tin khách hàng ở phiếu đặt 

### ISSUE THREAD

**Issue by BaoNgoc2211** [BaoNgoc2211/DAPM#41]
Steps:

Đăng nhập vào web role khách hàng
Tại trang home nhấn vào một sản phẩm bất kỳ và nhấn icon "+"
Nhấn vào giỏ hàng trên thanh navbar hiển thị thông tin giỏ hàng
Giảm sản phẩm về 0
Enviroment: Trên laptop HP
Trình duyệt: Google chrome

Result
Thông tin số điện thoại để ở trường địa chỉ
Thông tin địa chỉ để ở trường số điện thoại
![Bug 11](https://github.com/user-attachments/assets/9d1e122e-9c6b-42d4-8404-e652b67f6730)

Expected Result
Trường tên người nhận: Lực Handsome 
Chi tiết địa chỉ: 0354158627
Số điện thoại nhận hàng: 38 Văn Chung

**Comment by phuczu13** [comment]
ok
