### ISSUE TITLE
cập nhật món phụ -> Sai navbar

### ISSUE THREAD

**Issue by BaoNgoc2211** [BaoNgoc2211/DAPM#45]
step:
1. Đăng nhập vào hệ thống role cửa hàng
2. hiển thị thông tin sai

Enviroment: Trên laptop HP
Trình duyệt: Google chrome

Result: 
![navbar](https://github.com/user-attachments/assets/493e1d88-aef0-4874-b8ea-7538f4a46a80)
Expected Result: Món phụ trên thanh navbar

**Comment by phuczu13** [comment]
done
