### ISSUE TITLE
Cập nhật trạng thái đơn hàng Cửa Hàng -> Chuyển Tìm tài xế

### ISSUE THREAD

**Issue by BaoNgoc2211** [BaoNgoc2211/DAPM#47]
Steps:

Đăng nhập role cửa hàng
Điều hướng đến trang đơn hàng
Nhấp vào trang đaonw hàng đã nhận
Nhấp vào button Hoàn thành

Enviroment: Trên laptop HP
Trình duyệt: Google chrome

Result Chưa chuyển đến trang tìm kiếm xế
![donhang](https://github.com/user-attachments/assets/555e3a90-1d85-47b0-8636-fdbbd1759d35)
Expected Result: Chuyển đơn hàng qua đang tìm tài xế và role tài xế tại chờ xác nhận

**Comment by phuczu13** [comment]
cái này nè mng/-strong/-heart:>:o:-((:-h 
thường thì đặt là nó kiếm tài xế trước á/-strong/-heart:>:o:-((:-h 
tài xế nhận đơn rùi cửa hàng mới làm món
