### ISSUE TITLE
Cập nhật thông tin cửa hàn -> Ràng buộc Số điện thoại

### ISSUE THREAD

**Issue by BaoNgoc2211** [BaoNgoc2211/DAPM#48]
Steps:

1. Đăng nhập vào hệ thống role cửa hàng
2. Điều hướng đến trang thông tin của hàng

Result số điện thoại chỉ được nhập chữ số, bắt buộc 10 chữ số
![cuahang1](https://github.com/user-attachments/assets/4bd9ddb9-17ea-40f7-99c1-c397677f1338)
Expected Result: Chưa ràng buộc số điện

**Comment by phuczu13** [comment]
done
