### ISSUE TITLE
Cập nhật thông tin cửa hàng -> Email không hợp 

### ISSUE THREAD

**Issue by BaoNgoc2211** [BaoNgoc2211/DAPM#49]
Steps:

Đăng nhập vào role cửa hàng
Điều hướng đến trang thông tin cửa hàng
Nhập email không hợp lê (thiếu dấu chấm)

Result: Cập nhật thành 
![cuahang2](https://github.com/user-attachments/assets/78c636e1-896f-485a-ba94-48304cef8f87)
Expected Result: Cập nhật không thành công, hiển thị thông báo lỗi

**Comment by phuczu13** [comment]
done
