### ISSUE TITLE
Đăng ký tài khoản cửa hàng > Lỗi giao diện không đúng luồng

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#5]
Step (mô tả đến bước bị lỗi):
1. Khách hàng truy cập vào trang "Bắt đầu ... trở thành đối tác của chúng tôi".
2. Trang đăng nhập cửa hàng hiển thị.

Environment:
- Test trên Window 11.
- Sử dụng trình duyệt Microsoft Edge.

Actual Result (Mô tả lỗi):
![Lỗi sai luồng](https://github.com/user-attachments/assets/ad2ecbc3-282a-420a-b5f1-bce1a5f43382)
- Hệ thống hiện trang đăng nhập của khách hàng. Phải chọn nút "Đăng nhập dành cho cửa hàng" có trong trang để chuyển đến trang đăng nhập của cửa hàng.

Expected Result:
Hệ thống hiển thị trang đăng nhập của hàng.

**Comment by phuczu13** [comment]
done
