### ISSUE TITLE
Cập nhật thông tin -> Ràng buộc email

### ISSUE THREAD

**Issue by BaoNgoc2211** [BaoNgoc2211/DAPM#50]
Steps:

Đăng nhập role cửa hàng 
Điều hướng đến trang thông tin cửa hàng 
Cập nhật email không hợp lệ ( không phải là email)

Result: Cập nhật thành công
![cuahang3](https://github.com/user-attachments/assets/ae3db475-98cc-4d07-b029-94433a76666a)
Expected Result: Hiển thị thông báo lỗi

**Comment by phuczu13** [comment]
doneee
