### ISSUE TITLE
Xuất hóa đơn -> Chưa có chức năng

### ISSUE THREAD

**Issue by BaoNgoc2211** [BaoNgoc2211/DAPM#52]
Step:
Đăng nhập hệ thống role Cửa Hàng
Điều hướng đến trang đơn hàng 
Tại trạng thái đang làm món 
Chưa có chức năng xuất hóa đơn

Result: Chưa có chức năng xuất hóa đơn
![xua](https://github.com/user-attachments/assets/1bec1169-a0f2-4585-b035-8cc5ce30dddd)
Expected Result: Có button Xuất hóa đơn

**Comment by phuczu13** [comment]
done 
nma xuất ở hoàn thành chớ
