### ISSUE TITLE
Cập nhật món > (Sửa) Giá có thể sửa thành số âm

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#7]
Step (mô tả đến bước bị lỗi):
1. Đăng nhập vào role cửa hàng thành công
2. Chọn món nút "Sửa" của món có sẵn
3. Sửa giá món là số âm
4. Nhấn nút "Cập nhật"

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):
Sau khi nhập giá món là số âm vẫn có thể cập nhật món như bình thường

Expected Result:
Hệ thống thông báo giá không thể là số âm.

**Comment by phuczu13** [comment]
done
