### ISSUE TITLE
Cập nhật món > (Sửa) Phần mô tả gần như không có giới hạn ký tự

### ISSUE THREAD

**Issue by Eden314** [BaoNgoc2211/DAPM#9]
Step (mô tả đến bước bị lỗi):
1. Đăng nhập vào role cửa hàng thành công
2. Chọn món nút "Sửa" của món đã có bất kỳ
3. Sửa phần mô tả (copy 'đoạn văn' bất kỳ paste vào)
4. Nhấn nút "Sửa"

Environment:
- Test trên Window 11
- Sử dụng trình duyệt Microsoft Edge

Actual Result (Mô tả lỗi):
Trường dữ liệu mô tả có giới hạn dữ liệu rất rất dài, gần như không có giới hạn ký tự.
![image](https://github.com/user-attachments/assets/976b81d6-3ce1-4518-9925-73e15b360287)

Expected Result:
Hệ thống thông báo: Phần "Mô tả" vượt quá giới hạn ký tự.

**Comment by phuczu13** [comment]
donee
